spring.application.name=SERVICEMETADATA
server.port=8091

file.upload-dir=E://Logo
server.servlet.context-path=/services

spring.datasource.url = jdbc:postgresql://localhost:5432/metaData
spring.datasource.username = postgres
spring.datasource.password = 7754
spring.datasource.driver-class-name = org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.data.mongodb.database=service
spring.data.mongodb.uri=mongodb://localhost:27017/service

#Redis Conf
spring.data.redis.host=10.1.11.100
spring.data.redis.port=6379

eureka.client.service-url.defaultZone=http://10.1.11.100:7070/eureka/
eureka.instance.prefer-ip-address=true
#eureka.instance.prefer-ip-address=false

#Kaka Consumer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

kafka.update.credential.topic = updateUserCredential
kafka.update.credential.topic.grp = externalUserCredentialGrp

#Kafka producer
spring.kafka.bootstrap-servers=10.1.11.100:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=1
spring.kafka.producer.properties.request.timeout.ms=2000
spring.kafka.producer.properties.delivery.timeout.ms=3000
spring.kafka.producer.properties.max.block.ms=2000
spring.kafka.producer.properties.retry.backoff.ms=500

#kafka topics
kafka-topic-workflow-user-added = user-assignment-to-inbox-user-added
kafka-topic-workflow-user-removed = user-assignment-to-inbox-user-removed

aesServiceKey=e3nyflxiz86jb9ws
service.cookie.https=false
service.cookie.sameSite=none
service.secret.key=4l0b76ef14937c1c0ea519f8fc057a80fcd04a7420f3e8bcd0a7567c272e007b
service.expiration.time=60000

#elasticsearch
elasticsearch.host=10.1.11.126
elasticsearch.port=8091
elasticsearch.index.service-search=service_search
elasticsearch.index.form-search=form_search

kafka.outbox.publish.delay-ms=60000


#Unique Id generator config

id.generator.worker.id = 1
id.generator.datacenter.id =1

#Form Subscription
mail.form.publish.subject=Form Version Published Notification
mail.form.publish.body=<html><body style="font-family:Arial,Helvetica,sans-serif;font-size:14px;color:#333;"><p>Dear Service Definer,</p><p>This is to inform you that a new version of the attached form has been published successfully.</p><table style="border-collapse:collapse;"><tr><td><b>Service ID</b></td><td>: {SERVICE_ID}</td></tr><tr><td><b>Service Name</b></td><td>: {SERVICE_NAME}</td></tr></table><br/><p>Regards,<br/><b>Service Plus (e-SDT)</b></p></body></html>
kafka.topic.notification-configuration=service.notification.configuration
kafka.topic.filter.configuration=inbox-sentbox-filter-configuration
