CREATE TABLE schm_sp.payment_configuration_master (
    payment_option_id integer NOT NULL,
    payment_config_details jsonb
);


CREATE TABLE schm_sp.service_charge_detail (
    base_service_id integer,
    minor_version integer,
    service_id integer NOT NULL,
    version_no integer,
    c_date timestamp with time zone NOT NULL,
    id bigint NOT NULL,
    u_date timestamp with time zone,
    user_id bigint NOT NULL,
    charge_detail_json jsonb
);




ALTER TABLE schm_sp.service_charge_detail ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME schm_sp.service_charge_detail_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);




CREATE TABLE schm_sp.service_coverage (
    minor_version_no integer NOT NULL,
    service_id integer NOT NULL,
    state_id integer NOT NULL,
    version_no integer NOT NULL,
    c_date timestamp with time zone NOT NULL,
    u_date timestamp with time zone,
    user_id bigint NOT NULL,
    coverage_json jsonb NOT NULL
);



CREATE TABLE schm_sp.service_definition (
    base_service_id integer NOT NULL,
    minor_version_no integer NOT NULL,
    service_id integer NOT NULL,
    state_id integer NOT NULL,
    version_no integer NOT NULL,
    c_date timestamp with time zone NOT NULL,
    department_id bigint NOT NULL,
    u_date timestamp with time zone,
    user_id bigint NOT NULL,
    logo_path character varying(255) NOT NULL,
    definition_json jsonb NOT NULL
);


CREATE TABLE schm_sp.service_log (
    base_service_id integer NOT NULL,
    launch_flag character(1) NOT NULL,
    minor_version_no integer NOT NULL,
    service_id integer NOT NULL,
    version_no integer NOT NULL,
    c_date timestamp with time zone,
    launch_approved_by bigint,
    launched_by bigint,
    launched_date timestamp with time zone,
    u_date timestamp with time zone,
    tab_list character varying(100) NOT NULL,
    tenant_id character varying(255) NOT NULL,
    service_status character varying
);


CREATE TABLE schm_sp.service_master_data (
    master_id integer NOT NULL,
    name character varying(255),
    description text,
    data jsonb NOT NULL
);




CREATE TABLE schm_sp.service_mvel_event_mapping (
    event_id bigint NOT NULL,
    service_id integer,
    mvel_event_mapped_json jsonb,
    created_by bigint,
    created_on timestamp with time zone,
    version_no integer
);


ALTER TABLE schm_sp.service_mvel_event_mapping OWNER TO postgres;


CREATE SEQUENCE schm_sp.service_mvel_event_mapping_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE schm_sp.service_mvel_event_mapping_event_id_seq OWNED BY schm_sp.service_mvel_event_mapping.event_id;



CREATE TABLE schm_sp.service_mvel_funtion (
    minor_version_no integer,
    service_id integer NOT NULL,
    version_no integer,
    created_by bigint NOT NULL,
    created_on timestamp with time zone NOT NULL,
    id bigint NOT NULL,
    modified_by bigint,
    modified_on timestamp with time zone,
    minor_version_created character varying(255),
    name character varying(255),
    mvel_function_json jsonb NOT NULL
);



ALTER TABLE schm_sp.service_mvel_funtion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME schm_sp.service_mvel_funtion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE schm_sp.service_output_format (
    base_service_id integer,
    minor_version integer,
    service_id integer NOT NULL,
    version_no integer,
    c_date timestamp with time zone NOT NULL,
    id bigint NOT NULL,
    u_date timestamp with time zone zone,
    user_id bigint NOT NULL,
    output_format_json jsonb
);



ALTER TABLE schm_sp.service_output_format ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME schm_sp.service_output_format_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE schm_sp.service_process_flow (
    base_service_id integer,
    department_id integer NOT NULL,
    minor_version_no integer NOT NULL,
    service_id integer NOT NULL,
    state_id integer NOT NULL,
    version_no integer NOT NULL,
    c_date timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    u_date timestamp(6) without time zone,
    user_id bigint NOT NULL,
    draft_process_flow jsonb,
    process_flow_json jsonb
);



ALTER TABLE schm_sp.service_process_flow ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME schm_sp.service_process_flow_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE schm_sp.service_template (
    base_service_id integer NOT NULL,
    minor_version integer NOT NULL,
    service_id integer NOT NULL,
    version_no integer NOT NULL,
    c_date timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    u_date timestamp(6) without time zone,
    user_id bigint NOT NULL,
    form_id character varying(255) NOT NULL,
    instantiable_flag character varying(255),
    task_id character varying(255) NOT NULL,
    template_name character varying
);


ALTER TABLE schm_sp.service_template ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME schm_sp.service_template_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE schm_sp.spe_sequence_last_no (
    spdi_sequence_id integer NOT NULL,
    spdv_sequence_table character varying(100),
    spdi_last_num integer,
    spdv_modified_by character varying(100),
    spdd_modified_date date
);

ALTER TABLE ONLY schm_sp.service_mvel_event_mapping ALTER COLUMN event_id SET DEFAULT nextval('schm_sp.service_mvel_event_mapping_event_id_seq'::regclass);

ALTER TABLE ONLY schm_sp.payment_configuration_master
    ADD CONSTRAINT payment_configuration_master_pkey PRIMARY KEY (payment_option_id);

ALTER TABLE ONLY schm_sp.spe_sequence_last_no
    ADD CONSTRAINT pk_sequence PRIMARY KEY (spdi_sequence_id);

ALTER TABLE ONLY schm_sp.service_charge_detail
    ADD CONSTRAINT service_charge_detail_pkey PRIMARY KEY (id);

ALTER TABLE ONLY schm_sp.service_coverage
    ADD CONSTRAINT service_coverage_pkey PRIMARY KEY (service_id);

ALTER TABLE ONLY schm_sp.service_definition
    ADD CONSTRAINT service_definition_pkey PRIMARY KEY (service_id);

ALTER TABLE ONLY schm_sp.service_log
    ADD CONSTRAINT service_log_pkey PRIMARY KEY (service_id);

ALTER TABLE ONLY schm_sp.service_master_data
    ADD CONSTRAINT service_master_data_pkey PRIMARY KEY (master_id);

ALTER TABLE ONLY schm_sp.service_mvel_event_mapping
    ADD CONSTRAINT service_mvel_event_mapping_pkey PRIMARY KEY (event_id);

ALTER TABLE ONLY schm_sp.service_mvel_funtion
    ADD CONSTRAINT service_mvel_funtion_pkey PRIMARY KEY (id);

ALTER TABLE ONLY schm_sp.service_output_format
    ADD CONSTRAINT service_output_format_pkey PRIMARY KEY (id);

ALTER TABLE ONLY schm_sp.service_process_flow
    ADD CONSTRAINT service_process_flow_pkey PRIMARY KEY (id);

ALTER TABLE ONLY schm_sp.service_template
    ADD CONSTRAINT service_template_pkey PRIMARY KEY (id);

ALTER TABLE schm_sp.service_log
    ALTER COLUMN service_status TYPE integer;

--- 0042875: SP 2.0 | Provide APIs for External System Registration
--- 18 May 2026 (Start)
CREATE TABLE IF NOT EXISTS schm_sp.external_system_registration
(
    id bigint NOT NULL DEFAULT nextval('schm_sp.external_system_registration_id_seq'::regclass),
    client_id character varying COLLATE pg_catalog."default" NOT NULL,
    department_id integer,
    location_id character varying COLLATE pg_catalog."default",
    c_by character varying COLLATE pg_catalog."default",
    c_date timestamp with time zone,
    u_by character varying COLLATE pg_catalog."default",
    u_date timestamp with time zone,
    status character varying COLLATE pg_catalog."default",
    call_type character varying COLLATE pg_catalog."default",
    configuration_json jsonb,
    client_name character varying COLLATE pg_catalog."default",
    CONSTRAINT external_system_registration_pkey PRIMARY KEY (id)
)
--- 18 May 2026 (End)

ALTER TABLE schm_sp.external_system_registration
ALTER COLUMN location_id TYPE integer USING location_id::integer,
ALTER COLUMN c_by TYPE integer USING c_by::integer,
ALTER COLUMN u_by TYPE integer USING u_by::integer;

---	0042929: SP 2.0 ||Service - Definition: Issues related to service logo.

ALTER TABLE IF EXISTS schm_sp.service_definition DROP COLUMN IF EXISTS logo_path;

UPDATE schm_sp.service_definition
SET definition_json = jsonb_set(
    definition_json,
    '{logo}',
    '""'::jsonb
)
WHERE definition_json ? 'logo';

---External System User
CREATE TABLE IF NOT EXISTS schm_sp.external_system_user
(
    id BIGSERIAL PRIMARY KEY,
    external_system_reg_id BIGINT ,
    external_client_id character varying,
    user_id INTEGER,
    sign_no character varying,
    c_date timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

--0043190: SP 2.0 | User Assignment 
CREATE TABLE IF NOT EXISTS schm_sp.workflow_assignment
(
    holder_id character varying COLLATE pg_catalog."default" NOT NULL,
    base_service_id integer not null,
    service_id integer not null,
    task_id character varying COLLATE pg_catalog."default" not null,
    location_id character varying COLLATE pg_catalog."default" not null,
    user_id bigint,
    assigned_by bigint not null,
    version_no integer,
    crt_on timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    upd_on timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    tenant_id character varying COLLATE pg_catalog."default" not null,
    CONSTRAINT user_assignment_pkey PRIMARY KEY (holder_id)
);
create index schm_sp.workflow_assignment_idx on schm_sp.workflow_assignment (service_id, task_id, location_id );

CREATE TABLE schm_sp.workflow_assignment_history (

	id bigserial PRIMARY KEY,
    holder_id character varying COLLATE pg_catalog."default" NOT NULL,
    base_service_id integer not null,
    service_id integer not null,
    task_id character varying COLLATE pg_catalog."default" not null,
    location_id character varying COLLATE pg_catalog."default" not null,
    user_id bigint,
    assigned_by bigint not null,
    version_no integer,
    crt_on timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    upd_on timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    tenant_id character varying COLLATE pg_catalog."default" not null
);

--0043191: SP 2.0 | User Assignment 2

CREATE TABLE schm_sp.kafka_outbox_event (
    id CHARACTER VARYING PRIMARY KEY,
    topic CHARACTER VARYING NOT NULL,
    event_key CHARACTER VARYING,
    payload TEXT NOT NULL,
    status CHARACTER VARYING NOT NULL DEFAULT 'PENDING',
    retry_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMPTZ
);
--Notification 
CREATE TABLE IF NOT EXISTS schm_sp.notification_configuration
(
    notification_id bigserial,
    tenant_id character varying(100) COLLATE pg_catalog."default" NOT NULL,
    service_id integer NOT NULL,
    notification_name character varying(500) COLLATE pg_catalog."default" NOT NULL,
    channel character varying(50) COLLATE pg_catalog."default" NOT NULL,
    trigger_point_id character varying(100) COLLATE pg_catalog."default",
    task_id character varying(100) COLLATE pg_catalog."default",
    config_json jsonb,
    deleted_flag boolean NOT NULL DEFAULT false,
    created_by bigint,
    created_on timestamp with time zone,
    modified_by bigint,
    modified_on timestamp with time zone,
    CONSTRAINT notification_configuration_pkey PRIMARY KEY (notification_id)
);

--Alter script to rename column----
ALTER TABLE schm_sp.service_definition
RENAME COLUMN state_id TO clc_id;   

ALTER TABLE schm_sp.service_process_flow
RENAME COLUMN state_id TO clc_id;   

--Alter script to type conversion----
ALTER TABLE schm_sp.workflow_assignment
ALTER COLUMN assigned_by TYPE BIGINT;

ALTER TABLE schm_sp.workflow_assignment
ALTER COLUMN user_id TYPE BIGINT;

ALTER TABLE schm_sp.workflow_assignment_history
ALTER COLUMN assigned_by TYPE BIGINT;

ALTER TABLE schm_sp.workflow_assignment_history
ALTER COLUMN user_id TYPE BIGINT;


--Alter--
ALTER TABLE schm_sp.service_template
ADD COLUMN holder_id character varying

--Create form_publish_log table --
CREATE TABLE IF NOT EXISTS schm_sp.form_publish_log
(
    id bigint NOT NULL DEFAULT nextval('schm_sp.form_publish_log_id_seq'::regclass),
    user_id bigint NOT NULL,
    service_id integer NOT NULL,
    service_name character varying COLLATE pg_catalog."default" NOT NULL,
    task_id character varying COLLATE pg_catalog."default" NOT NULL,
    task_name character varying COLLATE pg_catalog."default" NOT NULL,
    holder_id character varying COLLATE pg_catalog."default" NOT NULL,
    form_id character varying COLLATE pg_catalog."default" NOT NULL,
    publish_form_id character varying COLLATE pg_catalog."default" NOT NULL,
    version integer NOT NULL,
    mode character varying COLLATE pg_catalog."default" NOT NULL,
    apply boolean,
    c_date timestamp with time zone NOT NULL,
    u_date timestamp with time zone,
    CONSTRAINT form_publish_log_pkey PRIMARY KEY (id)
)
---set process_flow_json for new spgd from lgd
UPDATE schm_sp.service_process_flow
SET process_flow_json = jsonb_set(
    process_flow_json,
    '{nodes}',
    (
        SELECT jsonb_agg(
            CASE
                WHEN node->'data' ? 'departments'
                THEN jsonb_set(
                        node #- '{data,departments}',
                        '{data,entities}',
                        '[]'::jsonb,
                        true
                     )
                ELSE node
            END
        )
        FROM jsonb_array_elements(process_flow_json->'nodes') AS node
    )
);

-------- Notification Configuration 
CREATE TABLE schm_sp.notification_provider_config
(
    id bigserial NOT NULL,
    type character varying NOT NULL,
    properties_json jsonb NOT NULL,
    c_user_id bigint NOT NULL,
    c_date timestamp with time zone NOT NULL,
    u_date timestamp with time zone,
    tenant_id character varying NOT NULL,
    clc_id integer,
    entity_id integer,
    location_id integer,
    status character(1) NOT NULL,
    remark character varying,
    PRIMARY KEY (id)
);	

---------------- Service Delivery Unit
ALTER TABLE IF EXISTS schm_sp.service_coverage
    RENAME TO service_delivery_unit;

ALTER TABLE IF EXISTS schm_sp.service_delivery_unit
    RENAME coverage_json TO delivery_unit_json;


ALTER TABLE IF EXISTS schm_sp.service_delivery_unit
    RENAME TO service_delivery_unit_definition;
    
ALTER TABLE IF EXISTS schm_sp.service_delivery_unit_definition
    ADD COLUMN source character varying;    
    
CREATE TABLE IF NOT EXISTS schm_sp.service_delivery_units
(
    id bigserial,
    tenant_id character varying COLLATE pg_catalog."default" NOT NULL,
    base_service_id integer NOT NULL,
    service_id integer NOT NULL,
    delivery_unit_level_id integer NOT NULL,
    delivery_unit_location_id integer NOT NULL,
    delivery_unit_location_name character varying COLLATE pg_catalog."default",
    activation_status integer NOT NULL default 0,
    activated_by bigint,
    activated_on timestamp with time zone,
    deactivated_by bigint,
    deactivated_on timestamp with time zone,
    remarks character varying COLLATE pg_catalog."default",
    cr_by bigint,
    c_date timestamp with time zone NOT NULL,
    up_by bigint,
    u_date timestamp with time zone,
    deleted_flag boolean NOT NULL DEFAULT false,    
    CONSTRAINT serivice_delivery_units_pkey PRIMARY KEY (id)
);

create index IF NOT EXISTS indx_tenant_service_level_name on 
schm_sp.service_delivery_units (tenant_id, service_id, delivery_unit_level_id, delivery_unit_location_name);

ALTER TABLE IF EXISTS schm_sp.service_delivery_units
    ADD CONSTRAINT fk_service_delivery_key FOREIGN KEY (service_id)
    REFERENCES schm_sp.service_log (service_id);

CREATE TABLE IF NOT EXISTS schm_sp.service_designated_officer_assignment
(
    assignment_id bigserial,
    base_service_id integer NOT NULL,
    service_id integer NOT NULL,
    delivery_unit_level_id integer NOT NULL,
    location_id integer NOT NULL,
    user_id bigint,
    designation_id integer,
    cr_by bigint,
    c_date timestamp with time zone,
    up_by bigint,
    u_date timestamp with time zone,
    deleted_flag boolean DEFAULT false,
    tenant_id character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT service_designated_officer_assignment_pkey PRIMARY KEY (assignment_id)
);
-- to add index
create index IF NOT EXISTS indx_tenant_srv_lvl_desg_asign on 
schm_sp.service_designated_officer_assignment (tenant_id, service_id,  delivery_unit_level_id, user_id);
-- to add foreign key
ALTER TABLE IF EXISTS schm_sp.service_designated_officer_assignment
    ADD CONSTRAINT fk_srv_designated_off_assgignment FOREIGN KEY (service_id)
    REFERENCES schm_sp.service_log (service_id);

------------- Notification Configuration
ALTER TABLE schm_sp.notification_configuration
ADD COLUMN base_service_id INTEGER NOT NULL DEFAULT 0;

ALTER TABLE schm_sp.notification_configuration
RENAME COLUMN deleted_flag TO active;
------Service name /abbrevation added---
ALTER TABLE schm_sp.service_definition
ADD COLUMN service_name character varying;

ALTER TABLE schm_sp.service_definition
ADD COLUMN service_abbreviation character varying;


UPDATE schm_sp.service_definition
SET
    service_name = definition_json ->> 'name',
    service_abbreviation = definition_json ->> 'abbreviation'
WHERE service_name IS NULL
   OR service_abbreviation IS NULL;

   
   ---------- service_inbox_outbox_filter ---------------
CREATE TABLE IF NOT EXISTS schm_sp.service_filter
(
    id bigserial NOT NULL,
    base_service_id bigint NOT NULL,
    service_id bigint NOT NULL,
    tenant_id character varying COLLATE pg_catalog."default" NOT NULL,
    filter_name character varying COLLATE pg_catalog."default" NOT NULL,
    tasks_json jsonb,
    filter_type character(1) COLLATE pg_catalog."default" NOT NULL,
    filter_condition character varying COLLATE pg_catalog."default" NOT NULL,
    filter_json jsonb,
    filter_status integer NOT NULL,
    cr_date timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    up_date timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cr_by bigint NOT NULL,
    CONSTRAINT service_filter_pkey PRIMARY KEY (id)
);

ALTER TABLE schm_sp.service_log 
	ADD COLUMN launch_doc_file_id character varying;



-----------------------------------AUA--------------------------
CREATE TABLE IF NOT EXISTS schm_sp.aua_providers
(
    id bigserial,
    provider_name character varying COLLATE pg_catalog."default" NOT NULL,
    description character varying COLLATE pg_catalog."default",
    active boolean NOT NULL DEFAULT true,
    cr_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    up_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tenant_id character varying COLLATE pg_catalog."default",
    CONSTRAINT aua_providers_pkey PRIMARY KEY (id),
    CONSTRAINT uk_aua_providers_name UNIQUE (provider_name)
);


CREATE TABLE IF NOT EXISTS schm_sp.aua_api_definitions
(
    id bigserial,
    provider_id bigint NOT NULL,
    api_code character varying COLLATE pg_catalog."default" NOT NULL,
    api_name character varying COLLATE pg_catalog."default" NOT NULL,
    operation_type character varying COLLATE pg_catalog."default" NOT NULL,
    api_version character varying COLLATE pg_catalog."default",
    protocol character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'HTTPS'::character varying,
    http_method character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'POST'::character varying,
    endpoint character varying COLLATE pg_catalog."default",
    description character varying COLLATE pg_catalog."default",
    active boolean NOT NULL DEFAULT true,
    cr_date timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    up_date timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tenant_id character varying COLLATE pg_catalog."default",
    xml_namespace character varying COLLATE pg_catalog."default",
    xml_namespace_version character varying COLLATE pg_catalog."default",
    CONSTRAINT aua_api_definitions_pkey PRIMARY KEY (id),
    CONSTRAINT uk_aua_api_definition UNIQUE (provider_id, api_code, api_version),
    CONSTRAINT fk_aua_api_def_provider FOREIGN KEY (provider_id)
        REFERENCES schm_sp.aua_providers (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS schm_sp.aua_api_messages
(
    id bigserial,
    api_definition_id bigint NOT NULL,
    message_type character varying COLLATE pg_catalog."default" NOT NULL,
    root_element character varying COLLATE pg_catalog."default" NOT NULL,
    xsd_content text COLLATE pg_catalog."default",
    xsd_version character varying COLLATE pg_catalog."default",
    xsd_hash character varying COLLATE pg_catalog."default",
    description character varying COLLATE pg_catalog."default",
    active boolean NOT NULL DEFAULT true,
    cr_date timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    up_date timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tenant_id character varying COLLATE pg_catalog."default",
    CONSTRAINT aua_api_messages_pkey PRIMARY KEY (id),
    CONSTRAINT uk_aua_api_message UNIQUE (api_definition_id, message_type),
    CONSTRAINT fk_aua_api_message_definition FOREIGN KEY (api_definition_id)
        REFERENCES schm_sp.aua_api_definitions (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS schm_sp.aua_api_fields
(
    id bigserial,
    message_id bigint NOT NULL,
    field_code character varying COLLATE pg_catalog."default" NOT NULL,
    field_name character varying COLLATE pg_catalog."default" NOT NULL,
    xpath character varying COLLATE pg_catalog."default" NOT NULL,
    data_type character varying COLLATE pg_catalog."default" NOT NULL,
    field_type character varying COLLATE pg_catalog."default" NOT NULL,
    required boolean NOT NULL DEFAULT false,
    multiple boolean NOT NULL DEFAULT false,
    sensitive boolean NOT NULL DEFAULT false,
    default_value character varying COLLATE pg_catalog."default",
    allowed_values jsonb,
    description character varying COLLATE pg_catalog."default",
    display_order integer,
    active boolean NOT NULL DEFAULT true,
    cr_date timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    up_date timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tenant_id character varying COLLATE pg_catalog."default",
    displayable boolean NOT NULL DEFAULT true,
    generation_type character varying COLLATE pg_catalog."default",
    CONSTRAINT aua_api_fields_pkey PRIMARY KEY (id),
    CONSTRAINT uk_aua_api_field UNIQUE (message_id, field_code),
    CONSTRAINT fk_aua_api_field_message FOREIGN KEY (message_id)
        REFERENCES schm_sp.aua_api_messages (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);



CREATE TABLE IF NOT EXISTS schm_sp.aua_api_field_mappings
(
    id bigserial,
    api_definition_id bigint NOT NULL,
    api_field_id bigint NOT NULL,
    source_type character varying COLLATE pg_catalog."default" NOT NULL,
    source_path character varying COLLATE pg_catalog."default",
    transformation character varying COLLATE pg_catalog."default",
    default_value character varying COLLATE pg_catalog."default",
    cr_date timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    up_date timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tenant_id character varying COLLATE pg_catalog."default",
    response_attribute_type character varying COLLATE pg_catalog."default",
    desired_response character varying COLLATE pg_catalog."default",
    service_id bigint,
    cr_by bigint,
	up_by bigint,
    provider_id bigint,
    CONSTRAINT aua_api_field_mappings_pkey PRIMARY KEY (id),
    CONSTRAINT uk_aua_api_mapping UNIQUE (api_definition_id, api_field_id, service_id),
    CONSTRAINT fk_aua_mapping_definition FOREIGN KEY (api_definition_id)
        REFERENCES schm_sp.aua_api_definitions (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_aua_mapping_field FOREIGN KEY (api_field_id)
        REFERENCES schm_sp.aua_api_fields (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_aua_mapping_service FOREIGN KEY (service_id)
        REFERENCES schm_sp.service_definition (service_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);
